# Generated by Django 3.0 on 2019-12-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191202_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='followup_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.Task'),
        ),
    ]
