# Generated by Django 2.2.6 on 2019-11-11 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191111_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('AC', 'Open'), ('CL', 'Completed'), ('CA', 'Cancelled')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 18, 33, 52, 538193, tzinfo=utc)),
        ),
    ]
