# Generated by Django 2.2.6 on 2019-11-19 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191119_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CL', 'Completed'), ('CA', 'Cancelled')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 3, 17, 22, 36, 537041, tzinfo=utc)),
        ),
    ]
