# Generated by Django 2.2.6 on 2019-11-19 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191119_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 3, 17, 24, 38, 901808, tzinfo=utc)),
        ),
    ]
