# Generated by Django 2.2.6 on 2019-11-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191119_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followup',
        ),
    ]
