# Generated by Django 2.2.6 on 2019-11-21 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_auto_20191119_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 23, 48, 2, 921093, tzinfo=utc)),
        ),
    ]
