# Generated by Django 3.0 on 2019-12-03 04:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_auto_20191202_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 4, 1, 59, 704397, tzinfo=utc)),
        ),
    ]
