# Generated by Django 2.2.6 on 2019-11-22 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0004_auto_20191121_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 6, 0, 33, 42, 574240, tzinfo=utc)),
        ),
    ]
