# Generated by Django 3.0 on 2019-12-03 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0004_auto_20191202_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 4, 5, 4, 404171, tzinfo=utc)),
        ),
    ]
