# Generated by Django 2.2.6 on 2019-11-30 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0005_auto_20191121_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 14, 17, 46, 27, 169140, tzinfo=utc)),
        ),
    ]
