# Generated by Django 2.2.6 on 2019-11-30 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0008_auto_20191130_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 14, 18, 34, 24, 654830, tzinfo=utc)),
        ),
    ]
