# Generated by Django 2.2.6 on 2019-11-30 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0009_auto_20191130_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 14, 18, 35, 8, 422583, tzinfo=utc)),
        ),
    ]
