# Generated by Django 2.2.6 on 2019-11-30 17:47

from django.db import migrations, models
import inspections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('frequency', models.CharField(choices=[(inspections.models.FrequencyChoices('Weekly'), 'Weekly'), (inspections.models.FrequencyChoices('Monthly'), 'Monthly'), (inspections.models.FrequencyChoices('Bi-annual'), 'Bi-annual'), (inspections.models.FrequencyChoices('Annual'), 'Annual'), (inspections.models.FrequencyChoices('Biennial'), 'Biennial'), (inspections.models.FrequencyChoices('Five-year'), 'Five-year')], max_length=5)),
                ('status', models.CharField(choices=[(inspections.models.StatusChoices('Pending'), 'Pending'), (inspections.models.StatusChoices('Active'), 'Active'), (inspections.models.StatusChoices('Complete'), 'Complete'), (inspections.models.StatusChoices('Cancelled'), 'Cancelled')], max_length=5)),
                ('date_last_completed', models.DateField()),
                ('date_next_due', models.DateField()),
                ('procedure', models.TextField()),
                ('estimated_cost', models.FloatField(default=0.0)),
            ],
        ),
    ]
