# Generated by Django 2.2.6 on 2019-11-30 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inspections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('frequency', models.CharField(choices=[('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('BIANNUAL', 'Bi-annual'), ('ANNUAL', 'Annual'), ('BIENNIAL', 'Biennial'), ('FIVE_YEAR', 'Five-year')], default=inspections.models.FrequencyChoices('Weekly'), max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default=inspections.models.StatusChoices('Pending'), max_length=32)),
                ('date_last_completed', models.DateField(blank=True, null=True)),
                ('date_next_due', models.DateField()),
                ('procedure', models.TextField()),
                ('estimated_cost', models.FloatField(default=0.0)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
