# Generated by Django 2.2.6 on 2019-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_auto_20191130_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date_last_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
